name: 'Azure Login'
description: 'Authenticate with Azure using a service principal'
author: 'Microsoft'

inputs:
  creds:
    description: 'Azure service principal credentials in JSON format'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
